"""
Script to post generated procrystalline lattices to users
"""

import yaml

def main():

    users = read_users()
    tweet_to_users(users)


def read_users():
    """Read users from file generated by get_users"""

    with open("../../output/users.tmp", "r") as f:
        users = yaml.load(f, Loader=yaml.FullLoader)
    return users


def tweet_to_users(users):
    """Post Tweet of procrystal to users"""

    for i, user in enumerate(users):
        lattice = read_lattice(i)
        post_lattice(user, lattice)

def read_lattice(id):
    """Read lattice with corresponding id"""

    with open(f"../../output/sq3_sample_{id}.dat", "r") as f:
        lattice = f.read()
    return lattice[:-3]


def post_lattice(user, lattice):
    """Mock Post lattice to user"""

    print(f"to {user}:\n")
    print(lattice)


if __name__ == "__main__":
    main()